### ISSUE TITLE
WP 5.9 Beta 4 - Images purchased with Connect Search do not remove watermark

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-inspirations#130]
I added a 123RF image to my page and purchased it. I see my receipt for the transaction. When I view the image in my library I still see the watermark it wasn't automatically replaced.
![connect-search](https://user-images.githubusercontent.com/20601160/147578883-a1097ccc-b555-4b56-abba-4d69563266e3.gif)

**Comment by bwmarkle** [comment]
We troubleshooted this last week. Turns out to be a caching issue.
