### ISSUE TITLE
login_headertitle filter is deprecated in 5.2

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-inspirations#18]
**Describe the bug**
The filter `login_headertitle` is deprecated in WordPress 5.2. This filter is used on line 81 in includes/class-boldgrid-inspirations-branding.php

**To Reproduce**
1. Enable WP_DEBUG_DISPLAY 
2. In a WordPress 5.2 installation, visit wp-login.php
3. The following notice appears:
```Notice: login_headertitle is deprecated since version 5.2.0! Use login_headertext instead. Usage of the title attribute on the login logo is not recommended for accessibility reasons. Use the link text instead. ```

**Expected behavior**
The plugin should not log this notice.

**Screenshots**
![Selection_628](https://user-images.githubusercontent.com/8019842/57339693-e2700e80-70ef-11e9-93d8-9ec994dc6a7c.png)

**Additional context**
Upon testing, replacing the filter with `login_headertext` works as expected.

**Comment by timelsass** [comment]
that should be fine, did you want to submit a PR since you've made the change locally?

**Comment by jessecowens** [comment]
Yes, I'll do so thank you.

**Comment by timelsass** [comment]
backwards compat addition: https://github.com/BoldGrid/boldgrid-inspirations/commit/037f474b68999d07291a37426ffb4ab77cdceaf4

**Comment by nicolepaschen** [comment]
This seems to have been addressed, closing ticket
