### ISSUE TITLE
Bug: GridBlock sets using Add New

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-inspirations#21]
**Describe the bug**
Creating a new page using the Add New option fails sometimes while the GridBlock sets are loading.  Multiple recent reports from the Facebook user group regarding this problem.

**To Reproduce**
1. Go to Add New under the Pages option in the Dashboard.
2. See the Loading latest from GridBlock sets message.
3. Loading times out and error message is displayed.

Reproducing this bug on command has been difficult, sometimes you will get the error and other times the content sets load as expected.

**Expected behavior**
GridBlock sets should load without errors.

### wp-core ###

version: 5.2
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/workspace/public_html/workspace
wordpress_size: loading...
uploads_path: /home/workspace/public_html/workspace/wp-content/uploads
uploads_size: loading...
themes_path: /home/workspace/public_html/workspace/wp-content/themes
themes_size: loading...
plugins_path: /home/workspace/public_html/workspace/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Resolve
version: 1.19.3
author: the BoldGrid team
author_website: https://www.boldgrid.com/the-team
parent_theme: none
theme_features: editor-style, automatic-feed-links, title-tag, html5, post-thumbnails, custom-background, infinite-scroll, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, menus, widgets
theme_path: /home/workspace/public_html/workspace/wp-content/themes/boldgrid-resolve

### wp-themes (20) ###

2017 Child: version: 1.0, author: Harry J.
Callaway: version: 1.2.3, author: The BoldGrid Team
Cobalt: version: 1.2.3, author: The BoldGrid Team
Diced: version: 1.24.3, author: The BoldGrid Team
Evolv: version: 1.24.3, author: The BoldGrid Team
Hifidel: version: 1.24.3, author: The BoldGrid Team
Hydra Child: version: 1.0, author: Harry J.
Hydra: version: 1.24.3, author: The BoldGrid Team
Pavilion: version: 1.24.3, author: The BoldGrid Team
Swifty: version: 1.2.3, author: The BoldGrid Team
Uptempo: version: 1.19.3, author: the BoldGrid team
Vacation: version: 1.24.3, author: The BoldGrid Team
Venetian: version: 1.17.3, author: The BoldGrid Team
Wedge: version: 1.15.3, author: The BoldGrid Team
Westview: version: 1.2.3, author: The BoldGrid Team
Free Education: version: 1.0.2, author: scorpionthemes
Twenty Fifteen: version: 2.4, author: the WordPress team (latest version: 2.5)
Twenty Nineteen: version: 1.3, author: the WordPress team (latest version: 1.4)
Twenty Seventeen: version: 2.1, author: the WordPress team (latest version: 2.2)
Twenty Sixteen: version: 1.9, author: the WordPress team (latest version: 2.0)

### wp-plugins-active (7) ###

BoldGrid Backup: version: 1.9.3, author: BoldGrid
BoldGrid Easy SEO: version: 1.6.2, author: BoldGrid <support@boldgrid.com>
BoldGrid Gallery: version: 1.5, author: BoldGrid.com <wpb@boldgrid.com>
BoldGrid Inspirations: version: 2.0.2, author: BoldGrid <support@boldgrid.com>
Post and Page Builder: version: 1.10.1, author: BoldGrid <support@boldgrid.com>
Post and Page Builder Premium: version: 1.0.2, author: BoldGrid
WPForms Lite: version: 1.5.2.3, author: WPForms

### wp-plugins-inactive (1) ###

Akismet Anti-Spam: version: 4.1.1, author: Automattic (latest version: 4.1.2)

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.07

### wp-server ###

server_architecture: Linux 3.10.0-042stab127.2 x86_64
httpd_software: Apache
php_version: 7.1.29 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.64.0 OpenSSL/1.0.2r
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.5.5-10.2.24-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/workspace/public_html/workspace/wp-content
WP_PLUGIN_DIR: /home/workspace/public_html/workspace/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by bwmarkle** [comment]
@jamesros161 please use this issue for removing "Add new".

**Comment by nicolepaschen** [comment]
This feature has been removed - blocks no longer show on Pages > Add New
