### ISSUE TITLE
WP Update Notice appears on screen during Inspirations Process

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-inspirations#28]
**Describe the bug**
When I went thru the Inspirations process while needing a WP Core update, I saw the update notice on the Inspirations screens. 

**To Reproduce**
1. Use an install with a pending core upgrade
2. Install Inspirations and start the process
3. See Upgrade Notice on all tabs during process

**Expected behavior**
I feel like the notice should be hidden.

**Screenshots**
![wp-upgrade-notice](https://user-images.githubusercontent.com/20601160/58912830-fa37b400-86e8-11e9-80c6-5e7439e3570c.PNG)

**Comment by cssjoe** [comment]
I already reported that in #17
