### ISSUE TITLE
Cannot verify email - button jumps around

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/boldgrid-inspirations#48]
The last WP core release added this verification screen. When I have Inspirations active I cannot verify the email address bc the button jumps to the right side of the screen for some reason. Happens in Firefox and Chrome.
Did not have this issue with Crio

![cannot-verify-email-jump](https://user-images.githubusercontent.com/20601160/70654791-04e97d80-1c25-11ea-8c8a-8439c21d8902.gif)

**Comment by bwmarkle** [comment]
Closing. Resolved via https://github.com/BoldGrid/boldgrid-inspirations/pull/58
