### ISSUE TITLE
Default Admin Dashboard Menu Item Reordering

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-inspirations#54]
**Is your feature request related to a problem? Please describe.**
Currently the Inspirations plugin reorganizes the admin dashboard menu items, specifically removing Appearance and replacing it with Customize.

**Describe the solution you'd like**
By default new installations should not be reordered to more closely align with WordPress standard.  Users should still have the option to reorder the menu if desired and users that currently have the option enabled should not see their menu change if this update is implemented.

**Comment by bwmarkle** [comment]
@joe9663  I'll try to get to this and get it released early next week

**Comment by DrLightman** [comment]
It changes the icon too, I had bad five minutes to find widgets screen too for a client, I ended up writing /wp-admin/widgets.php in the browser's address tab and that saved me from a bad impression; I wonder "why" this reorganization.

**Comment by nicolepaschen** [comment]
This has been completed
