### ISSUE TITLE
Change Add New behavior when creating Pages

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-inspirations#55]
**Is your feature request related to a problem? Please describe.**
Inspiration modifies the default behavior of the Add New option when creating pages to load GridBlock sets instead of the typical expected action.

**Describe the solution you'd like**
Leave Add New behavior unmodified and load GridBlock sets with a different selection or remove it entirely.

**Comment by bwmarkle** [comment]
Handled in a different ticket. done.
