### ISSUE TITLE
Bug Report: Installing GridBlock set with Add New

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-inspirations#7]
**Describe the bug**
Installing one of the available GridBlock sets using Add New does not complete, the Install button spins indefinitely.

**To Reproduce**
1. Install Inspirations
2. Select Pages > Add New
3. Click Install on any of the available GridBlock sets
4. Install process starts, but never completes and the button just spins.

**Expected behavior**
Installation should complete and the user should be taken to the page editing interface to begin customizations.

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 64.0.2 (64-bit)

**Additional context**
Multiple reports (5+) of this problem in the week of 1/21/19

**Comment by bwmarkle** [comment]
Hopefully this fix fill go out on Monday.
