### ISSUE TITLE
Fatal Error Call to a member function get_configs() on null

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-inspirations#70]
**Describe the bug**
Some users have reported that after updating to Inspirations 2.4.1, a fatal error occurs. This may be related to a conflict with Kirki libraries in certain 3rd-Party Themes.

**To Reproduce**
1. Install WordPress with the [Di Responsive theme](https://wordpress.org/themes/di-responsive/)
2. Install BoldGrid Inspirations 2.4.1 and activate
3. See error

**Expected behavior**
If possible, the call to get_configs() should check to see if the error will occur before making the call to avoid fatal conflicts with 3rd-Pary themes

**Stack Trace**
As reported by the user, here is the incomplete stack trace:
`An error of type E_ERROR was caused in line 165 of the file /home/(redacted)/public_html/wp-content/plugins/boldgrid-inspirations/vendor/boldgrid/boldgrid-inspirations-premium/src/Premium/Attribution.php. Error message: Uncaught Error: Call to a member function get_configs() on null in /home/(redacted)/public_html/wp-content/plugins/boldgrid-inspirations/vendor/boldgrid/boldgrid-inspirations-premium/src/Premium/Attribution.php:165 Stack trace: #0 /home/(redacted)/public_html/wp-includes/class-wp-hook.php(287): Boldgrid\Inspirations\Premium\Attribution->addControls(Array) #1 /home/(redacted)/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 /home/(redacted)/public_html/wp-content/themes/di-responsive/inc/kirki/kirki/deprecated/filters.php(29): apply_filters('kirki/fields', Array) #3 /home/(redacted)/public_html/wp-includes/class-wp-hook.php(287): {closure}(Array) #4 /home/(redacted)/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #5 /home/(redacted)/public_html/wp-content/themes/di-responsive/inc/kirki/kirki/core/class-kirki-init.php(243): apply_filters('kirki_fields', Array) #6 /home/(redacted)/public_html/wp-content/themes/di-responsive/inc/kirki/kirki/core/class-kirki-init.php(121): Kir`

**Additional context**
Error was reported in the [Facebook Group](https://www.facebook.com/groups/BGTeamOrange/permalink/913942895740402/) as well as the [Support Forum](https://www.boldgrid.com/feedback/communities/10/topics/9390-boldgrid-inspirations-plugin-activation-wordpress)

**Comment by bwmarkle** [comment]
2.4.2 just released to fix this issue.
